#!/bin/bash

git stash -q --keep-index

echo "Running git pre-commit hook"

EXIT_STATUS=0

./gradlew ktlintCheck --rerun-tasks || EXIT_STATUS=$?

./gradlew checkStyleChanged --rerun-tasks || EXIT_STATUS=$?

./gradlew lint --rerun-tasks || EXIT_STATUS=$?

git stash pop -q

# return 1 exit code if running checks fails
exit $EXIT_STATUS